apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui-kit
  namespace: lending
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ui-kit
  template:
    metadata:
      labels:
        app: ui-kit
    spec:
      containers:
        - name: ui-kit
          image: docker.lending/ui-kit
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: ui-kit
  namespace: lending
  labels:
    app: ui-kit
spec:
  selector:
    app: ui-kit
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
